### ISSUE TITLE
If arch description in timeloop support VARIABLE

### ISSUE THREAD

**Issue by yyuchenyi** [NVlabs/timeloop#229]
Hi! Thanks for your pioneering work. May I ask that if arch description in timeloop support VARIABLE like it in accelergy compound components? for example:
Want to do in compound_components like:
```
#a,b are variables
attributes:
     a: 8
     b: 8
subcomponents:
   - name: XXX[0..a-1]
      class: XXX
      attributes:
          width: a*b
```
but when I use like this in arch.yaml, timeloop or accelergy throw error
`  "terminate called after throwing an instance of 'std::invalid_argument" `
in log:
```
 ERROR       Location: arch attribute "XXXX"
 ERROR       Problem encountered: NameError: Name 'XXXX(_VARIABLE_NAME here_)' is not defined.
```
Variables value can changed by outer scripts so design space exploration will be more convenient.
Looking forward to your reply！
