### ISSUE TITLE
Input Access Count Mismatch in Timeloop ISPASS 2020 Tutorial

### ISSUE THREAD

**Issue by Jaesuk-Lee** [NVlabs/timeloop#295]
Hello!

While running the ISPASS 2020 tutorial ([timeloop-accelergy-exercises/workspace/tutorial_exercises/01_accelergy_timeloop_2020_ispass](https://github.com/Accelergy-Project/timeloop-accelergy-exercises/tree/master/workspace/tutorial_exercises/01_accelergy_timeloop_2020_ispass/timeloop)), I observed that applying the **input stationary dataflow to the MainMemory level** in the 1D convolution problem produced input access counts that differ from the theoretical values.

### Observed Mapping
```
Input-Stationary + Local Output-Stationary Mapping:
MainMemory [ Weights:96 (96) Inputs:18 (18) Outputs:512 (512) ] 
---------------------------------------------------------------
| for P in [0:16)
|   for K in [0:32) // Input-stationary

Buffer [ Weights:3 (3) Inputs:3 (3) Outputs:1 (1) ] 
---------------------------------------------------
|     for R in [0:3) // Output-stationary
|       << Compute >>
```
### Expected Behavior

I expected the results of this mapping to match those in the second row of the 'MainMemory accesses' table captured from the ISCA tutorial slideset below:
![image](https://github.com/user-attachments/assets/a8ccaa3b-6a19-4cc0-8dcd-8c81a7c0cf0e)

### Observed Behavior

However, the MainMemory Scalar Reads count turned out to be different. Specifically:
```
Level 2
-------
=== MainMemory ===
...
    STATS
    -----
...
    Inputs:
...
        Scalar reads (per-instance)   : 48 // expected P+R-1(W) but got P*R
```
I obtained the expected results when applying a Weight-Stationary mapping at the MainMemory level(as shown in the first row of the table).
I would like to understand why this difference occurs. 

Thanks.

**Comment by angshuman-parashar** [comment]
Could you please paste the exact YAMLs you used (you can concatenate them into a a single file and upload). Please also indicate which version of Timeloop you used.

**Comment by Jaesuk-Lee** [comment]
I used timeloop-model in Timeloop.v4 with TimeloopFE, as guided by the tutorial.
The input YAML file (parsed by TimeloopFE) is attached below.
The only change from [exercise 2 no-tiling](https://github.com/Accelergy-Project/timeloop-accelergy-exercises/tree/master/workspace/tutorial_exercises/01_accelergy_timeloop_2020_ispass/timeloop/02-model-conv1d%2Boc-2level) is the permutation attribute of MainMemory (PRK -> RKP).

You can observe the MainMemory->STATS->Inputs->Scalar reads = 48 (P $$\times$$ R).
However, I expected this to be P + R - 1 because:
```
   P    delta_size  num_epochs_
 -----  ----------  -----------
   0         R           1
  1-15       1          P-1
```

The same behavior is observed when I change the permutation in 'exercise 2 __tiled__ mapping'.


Attachment: Input YAML file parsed by timeloopFE
```
dumped_by_timeloop_front_end: true
architecture:
    version: '0.4'
    subtree:
      - name: System_top_level
        attributes:
            version: '0.4'
            technology: "40nm"
            global_cycle_seconds: 1e-9
            has_power_gating: false
            power_gated_at: null
        local:
          - name: MainMemory[1..1]
            class: SRAM
            attributes:
                depth: 32768
                width: 64
                datawidth: 8
                has_power_gating: false
                n_banks: 2
                cluster_size: 1
                reduction_supported: true
                multiple_buffering: 1
                min_utilization: 0
                allow_overbooking: false
                meshX: 1
                meshY: 1
                technology: "40nm"
                global_cycle_seconds: 1e-9
                power_gated_at: null
            required_actions:
              - write
              - update
              - leak
              - read
            enabled: true
          - name: Buffer[1..1]
            class: regfile
            attributes:
                depth: 64
                width: 8
                datawidth: 8
                has_power_gating: false
                n_banks: 2
                cluster_size: 1
                reduction_supported: true
                multiple_buffering: 1
                min_utilization: 0
                allow_overbooking: false
                meshX: 1
                meshY: 1
                technology: "40nm"
                global_cycle_seconds: 1e-9
                power_gated_at: null
            required_actions:
              - write
              - update
              - leak
              - read
            enabled: true
          - name: MACC[1..1]
            class: intmac
            attributes:
                width: 8
                has_power_gating: false
                meshX: 1
                meshY: 1
                technology: "40nm"
                global_cycle_seconds: 1e-9
                power_gated_at: null
            required_actions:
              - compute
            enabled: true
architecture_constraints:
    targets: []
problem:
    version: '0.4'
    shape:
        name: Conv1D_OC
        dimensions:
          - K
          - R
          - P
        data_spaces:
          - name: Weights
            projection:
              -   -   - K
              -   -   - R
            read_write: false
          - name: Inputs
            projection:
              -   -   - R
                  -   - P
            read_write: false
          - name: Outputs
            projection:
              -   -   - K
              -   -   - P
            read_write: true
        coefficients: []
    instance:
        K: 32
        R: 3
        P: 16
        densities: {}
compound_components:
    version: '0.4'
    classes: []
mapping:
  - target: MainMemory
    type: temporal
    factors: R=1,P=16,K=32
    permutation: RKP
  - target: Buffer
    type: temporal
    factors: R=3,P=1,K=1
    permutation: RPK
mapper:
    version: '0.4'
    out_prefix: timeloop-mapper
    num_threads: 8
    optimization_metric: []
    search_size: null
    timeout: 1000
    victory_condition: null
    sync_interval: null
    log_interval: 1
    log_oaves: false
    log_oaves_mappings: false
    log_stats: false
    log_suboptimal: false
    live_status: false
    diagnostics: false
    penalize_consecutive_bypass_fails: false
    emit_whoop_nest: false
    max_temporal_loops_in_a_mapping: -1
    algorithm: hybrid
    filter_revisits: false
    max_permutations_per_if_visit: 16
mapspace:
    version: '0.4'
    template: uber
globals:
    version: '0.4'
    environment_variables: {}
    expression_custom_functions: []
    accelergy_plug_ins: []

```
