### ISSUE TITLE
About how to use the feature layout loop

### ISSUE THREAD

**Issue by tuvaluhk** [NVlabs/timeloop#312]
I noticed that a new feature named "layoutloop" has been introduced in the repository. As I read the code and comments, it seems realizing a new cycle/perf estimate method which is different to the bandwidth method. 

I really want to try this new feature, however, though I try adding  configuration to example as below:

```
layout:
  - target: MainMemory
    type: interline
    factors: M=4 N=4 K=4
    permutation: MNK

  - target: Buffer
    type: interline
    factors: M=1 N=1 K=1
    permutation: MNK

  - target: MACC
    type: interline
    factors: M=1 N=1 K=1
    permutation: MNK
```
It seems that MACC is part of  `StorageLevel()` and get check when constructing `Model` in `model.cpp:197`:
```
  if (existing_layout){
    std::map<std::string, std::pair<uint32_t, uint32_t>> externalPortMapping;
    for (auto i: arch_specs_.topology.LevelNames())
        externalPortMapping[i] = {arch_specs_.topology.GetStorageLevel(i)->num_ports.Get(), arch_specs_.topology.GetStorageLevel(i)->num_ports.Get()};

    layout_ = layout::ParseAndConstruct(compound_config_node_layout, workload_, externalPortMapping);
    
    layout_initialized_ = true;

    layout::PrintOverallLayout(layout_);
  }
```
It reports that the MACC level doesn't have `num_banks `attribute and fail.

```
timeloop-model: include/model/attribute.hpp:62: T model::Attribute<T>::Get() const [with T = long unsigned int]: Assertion `specified_' failed.
```
Specifically, I would like to know:

- The purpose of the layoutloop feature.

- Any configuration or setup required.

- An example/test of how to implement or use it.

Thank you for your work on this project and for your help!
