### ISSUE TITLE
Question about updates not contributing towards writes

### ISSUE THREAD

**Issue by vmiheer** [NVlabs/timeloop#80]
Hi @angshuman-parashar,
If I understand correctly, timeloop supports `O += A * B` only (and not `O = A * B`). Because there is only "read-write" data space. I tried simple vector dot product:

<details>
<summary>mac.yaml</summary>

```yaml
---
architecture:
  version: 0.3
  subtree:
    - name: system
      local:
        - name: DRAM
          class: DRAM
          attributes:
            type: LPDDR4
            width: 64
            block-size: 4
            word-bits: 16
            read_bandwidth: 1024
            write_bandwidth: 1024
      subtree:
        - name: PE
          local:
            - name: RegisterFile
              class: regfile
              attributes:
                depth: 3
                width: 8
                word-bits: 8
                read_bandwidth: 2
                write_bandwidth: 4
            - name: MACC
              class: intmac
              attributes:
                datawidth: 8
problem:
  shape:
    name: dot
    dimensions:
      - I
      - J
      - K
    data-spaces:
      - name: Weights
        projection:
          - - - I
          - - - K
      - name: Inputs
        projection:
          - - - K
          - - - J
      - name: Outputs
        projection:
          - - - I
          - - - J
        read-write: "True"
  instance:
    I: 1
    J: 1
    K: 1
mapping:
  - target: RegisterFile
    type: temporal
    permutation: IJK
    factors: I=1 J=1 K=1
  - target: DRAM
    type: temporal
    permutation: IJK
    factors: I=1 J=1 K=1
``` 
</details>

The register read bandwidth is 2. But for update, shouldn't it need to have read bandwidth of 3 (2 inputs and 1 output reads)? It's due to [updates are accounted for reads but not for writes](https://github.com/NVlabs/timeloop/blob/db033564c443c2dfa519427034e7cc2ceece3fda/src/model/buffer.cpp#L773).
Am I missing something obvious?
<details>
<summary> print from calculatePerformance function</summary>

```
================RegisterFile================
--------------------------------------------------------------------------------
RegisterFileDataspace: Weights
RegisterFiletotal_read_accesses: 1
RegisterFiletotal_write_accesses: 1
RegisterFilecompute_cycles: 1
unconstrained_read_bandwidth: 1
unconstrained_write_bandwidth: 1
--------------------------------------------------------------------------------
RegisterFileDataspace: Inputs
RegisterFiletotal_read_accesses: 1
RegisterFiletotal_write_accesses: 1
RegisterFilecompute_cycles: 1
unconstrained_read_bandwidth: 1
unconstrained_write_bandwidth: 1
--------------------------------------------------------------------------------
RegisterFileDataspace: Outputs
RegisterFiletotal_read_accesses: 0
RegisterFiletotal_write_accesses: 2
RegisterFilecompute_cycles: 1
unconstrained_read_bandwidth: 0
unconstrained_write_bandwidth: 2
```
</details>

**Comment by angshuman-parashar** [comment]
Timeloop is looking at your mapping and indexing expressions and deducing that the outputs are only ever written once and never actually updated, so it doesn't pay the cost of reading them. Basically the first read of an output update is elided (i.e., it's a pure write instead of a read-modify-write)

**Comment by vmiheer** [comment]
I am sorry, I don't understand. If the expression is `O += op(A, B)`, O's initial value needs to be read from dram into register and then mac op need to happen. Or am I assuming the wrong expression?

**Comment by angshuman-parashar** [comment]
Initial value in DRAM is assumed to be initialized to 0, which allows the first write to be elided. If you wish to disable this behavior you can comment out the `-partition_size` terms on lines 566 and 574 of buffer.cpp, and in whichever network modules you are using.

**Comment by vmiheer** [comment]
Awesome thank you!

**Comment by vmiheer** [comment]
Sorry I missed to ask about this case:
Consider:
```
MainMemory [ Weights:16 Inputs:16 Outputs:16 ] 
----------------------------------------------
| for K in [0:4)

GlobalBuffer [ Weights:4 Inputs:4 Outputs:16 ] 
----------------------------------------------
|   for K in [0:1)
|     for J in [0:4) (Spatial-Y)
|       for I in [0:4) (Spatial-X)

RegisterFile [ Weights:1 Inputs:1 Outputs:1 ] 
---------------------------------------------
|         for K in [0:1)
```

In this case, due to read elision, there are 3 reg reads, which is okay (skipped first read as it was 0). But write accesses are 5 (4 updates + 1 fill). If I understand correctly, fill is for bringing in all the data necessary from above memory level to this level before executing loops at this memory level. If the read elision was intended then why there is 1 fill? The same goes for SRAM (Global Buffer), there is no read of SRAM for the output buffer which makes sense, but why there is 1 fill of size 16? Is my understanding of fills wrong? Is read elision one way (writes happen to this level, even though corresponding reads don't happen at the level above)?

<details>
<summary>3 level arch</summary>

```yaml
---
architecture:
  version: 0.2

  subtree:
  - name: System

    local:
    - name: MainMemory
      class: DRAM
      attributes:
        width: 256
        block-size: 32
        word-bits: 8

    subtree:
    - name: Chip
      attributes:
        technology: 40nm

      local:
      - name: GlobalBuffer # 256KB buffer
        class: SRAM
        attributes:
          depth: 8388608
          width: 256
          block-size: 32
          word-bits: 8

      subtree:
      - name: PE [0..15]
        local:
        - name: RegisterFile
          class: regfile
          attributes:
            depth: 3
            width: 8
            block-size: 1
            word-bits: 8
            meshX : 4
        - name: MACC
          class: intmac
          attributes:
            datawidth: 8
            meshX : 4
problem:
  shape:
    name: dot
    dimensions:
      - I
      - J
      - K
    data-spaces:
      - name: Weights
        projection:
          - - - I
          - - - K
      - name: Inputs
        projection:
          - - - K
          - - - J
      - name: Outputs
        projection:
          - - - I
          - - - J
        read-write: "True"
  instance:
    I: 4
    J: 4
    K: 4
mapping:
  - target: RegisterFile
    type: temporal
    permutation: IJK
    factors: I=1 J=1 K=1
  - target: GlobalBuffer
    type: temporal
    permutation: IJK
    factors: I=1 J=1 K=1
  - target: GlobalBuffer
    type: spatial
    permutation: IJK
    factors: I=4 J=4 K=1
    split: 1
  - target: MainMemory
    type: temporal
    permutation: KJI
    factors: I=1 J=1 K=4
```
</details>

<details><summary>
ComputePerformance output:
</summary>

```
================RegisterFile================
--------------------------------------------------------------------------------
RegisterFileDataspace: Weights
RegisterFiletotal_read_accesses: 4
RegisterFiletotal_write_accesses: 4
RegisterFilecompute_cycles: 4
unconstrained_read_bandwidth: 1
unconstrained_write_bandwidth: 1
--------------------------------------------------------------------------------
RegisterFileDataspace: Inputs
RegisterFiletotal_read_accesses: 4
RegisterFiletotal_write_accesses: 4
RegisterFilecompute_cycles: 4
unconstrained_read_bandwidth: 1
unconstrained_write_bandwidth: 1
--------------------------------------------------------------------------------
RegisterFileDataspace: Outputs
RegisterFiletotal_read_accesses: 3
RegisterFiletotal_write_accesses: 5
RegisterFilecompute_cycles: 4
unconstrained_read_bandwidth: 0.75
unconstrained_write_bandwidth: 1.25
================GlobalBuffer================
--------------------------------------------------------------------------------
GlobalBufferDataspace: Weights
GlobalBuffertotal_read_accesses: 16
GlobalBuffertotal_write_accesses: 16
GlobalBuffercompute_cycles: 4
unconstrained_read_bandwidth: 4
unconstrained_write_bandwidth: 4
--------------------------------------------------------------------------------
GlobalBufferDataspace: Inputs
GlobalBuffertotal_read_accesses: 16
GlobalBuffertotal_write_accesses: 16
GlobalBuffercompute_cycles: 4
unconstrained_read_bandwidth: 4
unconstrained_write_bandwidth: 4
--------------------------------------------------------------------------------
GlobalBufferDataspace: Outputs
GlobalBuffertotal_read_accesses: 0
GlobalBuffertotal_write_accesses: 32
GlobalBuffercompute_cycles: 4
unconstrained_read_bandwidth: 0
unconstrained_write_bandwidth: 8
================MainMemory================
```
</details>
